### ISSUE TITLE
Criação de testes Unitários e projeto baseado no poetry

### ISSUE THREAD

**Issue by joepreludian** [lipe14-ops/brasilapy#1]
Hey @lipe14-ops! Bom dia, man!
Estava dando uma olhada no seu repositório e gostei bastante da qualidade do código escrito! Parabéns!

Eu gostaria de saber se voce está aberto a aceitar PRs com algumas melhorias. Das quais eu consigo me recordar agora, seriam 5:

* Adicionar Testes e Cobertura de código; Pensei em criar um projeto simples em cima do pyenv pra testar sua API.
* Criar uma ação no github actions pra validar eventuais implementações no seu codebase;
* Usar um projeto baseado no poetry. Acho ele bacana pois pode nos ajudar a manter um track das versões por meio dos lock file ao mesmo tempo que dá pra ser utilizado em instalações em modo desenvolvimento. Ele já encapsula o projeto dentro de um virtual env e conversa bem com o pyenv.
* Adicionar rotinas do `pre-commit` para pré-validações de código, linting, etc.
* Adicionar o `__pycache__` nos arquivos do gitignore.

Acredito que, com esses pontos, seu projeto poderia ser facilmente ser mantido sem perder a qualidade e esmero que voce colocou nele.

Bom, mas é só uma sugestão, tá? Eu gostaria de usá-lo nos meus projetos tbm, por isso que acho interessante criar esse arcabouço pra que outras pessoas possam contribuir também.

Bom, o que me diz? =)
Abraço!

**Comment by lipe14-ops** [comment]
# OPA @joepreludian !!!

Que bom que vc gostou do projeto... Muito boa as observações que foram feitas e sim... Estou aberto a melhorias fique a totalmente a vontade para fazer os PRs.
 
Obrigado :)

**Comment by joepreludian** [comment]
Que coisa boa, amigo.
Claro. Irei criar PRs então para cada um dos pontos. Obrigado.

**Comment by lipe14-ops** [comment]
Desde de já muito obrigado pela contribuição!!!
