### ISSUE TITLE
Deployment do projeto

### ISSUE THREAD

**Issue by joepreludian** [lipe14-ops/brasilapy#4]
Olá @lipe14-ops. Coisa rápida, amigo.
Gostaria de lhe pedir uma coisa para a próxima PR;

Por favor, no seu repositório, crie os seguintes secrets:

* CODECOV_TOKEN -> pra o report do Code Coverage
* PYPI_PASSWORD -> Voce pega no seu PyPI para que o github actions possa fazer o deployment para o repo do PyPI.

Para pegar o PyPI API token, só seguir os primeiros passos desse tutorial: 
https://towardsdatascience.com/how-to-publish-a-python-package-to-pypi-using-poetry-aa804533fc6f

Assim que criares, me avisa para que eu possa iniciar uma nova PR adicionando pipelines de teste, linting e deployment. =)

**Comment by joepreludian** [comment]
Ahh, também voce precisará mais de 2:

* GH_SONAR -> Voce precisa criar um Github access token com permissão para leitura do repositório; (pra orientar o Sonarcloud no último commit)
* SONARCLOUD_GH -> Esse voce cria no sonarcloud para nosso projeto. com isso ele receberá as notas da análise estática, e cobertura de código. =)

**Comment by joepreludian** [comment]
Acho que já sei o que houve. Você precisa modificar, na pipeline dr CICD,
pra configurar seu projeto e workspace lá no sonarcloud. Farei uma nova PR
com a fix pra você.

**Comment by lipe14-ops** [comment]
muito obrigado!!! (esse é o tal do junior rsrs)

**Comment by lipe14-ops** [comment]
bom tudo feito... mas no ultimo merge deu falha no deployment pq o teste tinha rodado anteriormente...

deu tudo certo!!!

**Comment by joepreludian** [comment]
O sonar cloud funcionou?

**Comment by lipe14-ops** [comment]
sim tudo funcionando...

**Comment by joepreludian** [comment]
Perfect!! 🥳
