### ISSUE TITLE
Criar documento de "como contribuir"

### ISSUE THREAD

**Issue by joepreludian** [lipe14-ops/brasilapy#6]
Acho que é importante criarmos um documento no `README.md` ensinando a reproduzir o environment. 
Um dos pontos que poderíamos tratar seria:

* Instalação das dependencias com pacotes de desenvolvimento;
* instalação do pre-commit;
* Configuração do pre-commit  para avaliar a cada push;

Em suma, criar um guia que gire em torno dos comandos:

    $ poetry install --with dev

    $ poetry shell

    $ pre-commit install  # Para instalar os git-hooks

    $ pre-commit run --all-files  # Para rodar os lintings e o black para limpar o código

    $ mypy .  # para rodar o teste do mypy

Caso ninguém o faça, eu posso construir =)

**Comment by lipe14-ops** [comment]
certo é algo importante para o crescimento do projeto...

**Comment by lipe14-ops** [comment]
certo é algo realmente importante para o projeto... É sempre bom bom envolver que queira ajudar.

**Comment by lipe14-ops** [comment]
certo é algo realmente importante para o projeto... É sempre bom bom envolver que queira ajudar.

Fique à vontade para a implementação!!!!

**Comment by joepreludian** [comment]
Essa issue já foi finalizada. =) Podemos encerrar com sucesso.
